### PR TITLE
Pin chef-ingredients version in shell snippet

### LINKED ISSUE #137: bump chef-ingredient dependency
### Cookbook version
5.2.0

### Chef-client version
12.19.36

### Platform Details
centos7

### Scenario:
Chef a Chef Server (install)

### Steps to Reproduce:
dna.json
```json
{
  "fqdn": "hostname.domainname.tld",
   "chef_client": {
     "init_style": "none"
   },
  "chef-server": {
    "accept_license": true,
    "addons": ["manage","push-jobs-server","reporting"],
    "api_fqdn": "chef12.anaplan-np.net",
    "configuration": "nginx['ssl_certificate'] = '/var/chef/ssl/hostname.domainname.tld'\nnginx['ssl_certificate_key'] = '/var/chef/ssl/hostname.domainname.tld'",
    "topology": "standalone",
    "version": "12.14.0"
  },
  "firewall": {
    "allow_established": true,
    "allow_ssh": true
  },
  "system": {
    "delay_network_restart": false,
    "domain_name": "anaplan-np.net",
    "manage_hostsfile": true,
    "short_hostname": "chef12"
  },
  "tags": []
}
```

Required cookbook sync:
```bash
sudo rm -rf /var/chef/cookbooks ; sudo mkdir -p /var/chef/cookbooks
sudo rm -rf /var/chef/cache     ; sudo mkdir -p /var/chef/cache
sudo rm -rf /var/chef/ssl       ; sudo mkdir -p /var/chef/ssl

for DEP in apt apt-chef chef-client     ; do curl -sL https://supermarket.chef.io/cookbooks/${DEP}/download | sudo tar xzC /var/chef/cookbooks; done
for DEP in chef_handler chef-ingredient ; do curl -sL https://supermarket.chef.io/cookbooks/${DEP}/download | sudo tar xzC /var/chef/cookbooks; done
for DEP in compat_resource chef-server  ; do curl -sL https://supermarket.chef.io/cookbooks/${DEP}/download | sudo tar xzC /var/chef/cookbooks; done
for DEP in chef-sugar cron firewall     ; do curl -sL https://supermarket.chef.io/cookbooks/${DEP}/download | sudo tar xzC /var/chef/cookbooks; done
for DEP in hostsfile logrotate          ; do curl -sL https://supermarket.chef.io/cookbooks/${DEP}/download | sudo tar xzC /var/chef/cookbooks; done
for DEP in packagecloud system yum      ; do curl -sL https://supermarket.chef.io/cookbooks/${DEP}/download | sudo tar xzC /var/chef/cookbooks; done
for DEP in yum-chef windows             ; do curl -sL https://supermarket.chef.io/cookbooks/${DEP}/download | sudo tar xzC /var/chef/cookbooks; done

sudo chown -R root:root /var/chef

exit 0
```

Note: Attempts to `berks vendor` the chef-server cookbook also resulted in the latest chef-ingredient cookbook download (2.0.1)

Attempt Installation:
`sudo chef-solo -j .chef/dna.json -o 'recipe[system::default],recipe[chef-server::default],recipe[chef-server::addons]'`

### Expected Result:
Chef server is installed

### Actual Result:
```
aws_instance.chef-server (remote-exec): ================================================================================
aws_instance.chef-server (remote-exec): Error Resolving Cookbooks for Run List:
aws_instance.chef-server (remote-exec): ================================================================================

aws_instance.chef-server (remote-exec): Missing Cookbooks:
aws_instance.chef-server (remote-exec): ------------------
aws_instance.chef-server (remote-exec): Could not satisfy version constraints for: chef-ingredient

aws_instance.chef-server (remote-exec): Expanded Run List:
aws_instance.chef-server (remote-exec): ------------------
aws_instance.chef-server (remote-exec): * system::default
aws_instance.chef-server (remote-exec): * chef-server::default
aws_instance.chef-server (remote-exec): * chef-server::addons

aws_instance.chef-server (remote-exec): Platform:
aws_instance.chef-server (remote-exec): ---------
aws_instance.chef-server (remote-exec): x86_64-linux

aws_instance.chef-server (remote-exec):
aws_instance.chef-server (remote-exec): Running handlers:
aws_instance.chef-server (remote-exec): [2017-04-07T17:41:35+00:00] ERROR: Running exception handlers
aws_instance.chef-server (remote-exec): Running handlers complete
aws_instance.chef-server (remote-exec): [2017-04-07T17:41:35+00:00] ERROR: Exception handlers complete
aws_instance.chef-server (remote-exec): Chef Client failed. 0 resources updated in 01 seconds
aws_instance.chef-server (remote-exec): [2017-04-07T17:41:35+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
aws_instance.chef-server (remote-exec): [2017-04-07T17:41:35+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
aws_instance.chef-server (remote-exec): [2017-04-07T17:41:35+00:00] ERROR: 412 "Precondition Failed"
aws_instance.chef-server (remote-exec): [2017-04-07T17:41:35+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

Root issue: chef-ingredient restriction in this cookbook is set to `~> 1.1`, but `~>` excludes 2.x builds. Either bump to `~> 2.0.0` or remove pessimism

### PR DESCRIPTION
**Pull request by unixorn**
### Description
When I tried to install chef-server with the current version of the
cookbook from github, I got the same

```
Could not satisfy version constraints for: chef-ingredient
```

error that is detailed in #137.

This updates README.md to make it easier for people to get started.

### Issues Resolved

It doesn't resolve #137, but it does document the workaround.

### Check List

This PR is a documentation-only change.

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by unixorn** [comment]
Ok, that's weird, I wonder why a markdown change caused an error on Ubuntu 16.

**Comment by sirhopcount** [comment]
Hi,

I found a small error with the suggested solution. The line  for unpacking the tar ball seems to have a few typo's (probably a copy/past error).

I had to change the line:

``
sudo tar xvzC chef-ingredient 1.1.0.tar.gz /var/chef/cookbooks && rm -f chef-ingredient 1.1.0.tar.gz
``

into

``
sudo tar xvzf chef-ingredient-1.1.0.tar.gz -C /var/chef/cookbooks && rm -f chef-ingredient-1.1.0.tar.gz
``

In order to get it working.

**Comment by unixorn** [comment]
Still choking on Ubuntu 16.04, even though this is just a markdown change.

**Comment by bshaw** [comment]
+1
Applying your documented fix to my script provides a workaround for #137.

**Comment by tas50** [comment]
We're pulling in the latest chef-ingredient now and I've updated the instructions to remove the other deps that aren't needed at this point. I'm going to close this out at this point.

**Comment by unixorn** [comment]
ok @tas50. I'm still curious why a markdown-only change was failing tests, and only on Ubuntu.

**Comment by tas50** [comment]
It's hard to tell since the output in that particular resource is suppressed due to the sensitive property being set. It may have just been a timeout somewhere in the install process.

**Pull request closed without merging**
