### PR TITLE
Digitalocean

### PR DESCRIPTION
**Pull request by stephenlauck**
Using the forked gem kitchen-digital_ocean and fixing syntax in the kitchen cloud yaml.

Also added the apt cookbook to the Berksfile since it's used in the kitchen cloud also.

### CODE REVIEW

**Comment by jtimberman** [comment]
Why is apt required?

**Comment by stephenlauck** [comment]
Apt isn't required, but it was in the cloud yml and not in the Berksfile. So the options are remove it from the kitchen file or put the dependency in the Berksfile.

**Comment by jtimberman** [comment]
Remove it from the .kitchen.cloud.yml. I see no reason why that is required anymore.

**Comment by stephenlauck** [comment]
Removed apt.

**Comment by jtimberman** [comment]
Cool. I've never used DO so I defer to @someara :cake:

**Comment by someara** [comment]
+1 shipitsquirrel

**Pull request merged**
